### ISSUE TITLE
[Conta] Usuário cria conta

### ISSUE THREAD

**Issue by decoporteira** [TreinaDev/td11-cola-bora#2]
Eu como visitante, quero criar minha conta para acessar os recursos do sistema.

- [x] Dados obrigatórios: CPF, email, senha e confirmação de senha.
- [x] CPF e email únicos.
- [x] Ser redirecionado para criação de perfil.
- [x] Usuário faz login
- [x] Usuário faz logout

**Comment by fredericomozzato** [comment]
Adicionamos validação de CPF na criação de conta usando a gem [cpf_cnpj](https://rubygems.org/gems/cpf_cnpj).

Para fazer o fluxo completo de um usuário acessando a aplicação adicionamos mais dois critérios de aceite: que um usuário cadastrado consiga fazer login e também logout.

O redirecionamento de perfil depende da issue de criação de perfil, para não deixarmos de completar o critério criamos o controller de perfis com apenas a action `edit` e uma rota para ela. Assim podemos fazer o redirecionamento sem criar muitos conflitos.
