### ISSUE TITLE
[Projeto] Usuário edita projetos

### ISSUE THREAD

**Issue by olucasaguilar** [TreinaDev/td11-cola-bora#23]
Eu, como lider de um projeto, quero poder editar os detalhes, para que eu possa alterar os dados do mesmo.

- Remover a listagem `Todos os Projetos`. Ela foi implementada, porém o cliente disse que os projetos devem ser mais 'privados'. (Já implementado, falta criar um index de projetos que o usuário colabora, mas não é lider, ja está nos rascunhos do backlog)

- Criar um botão editar dentro do show do projeto~ (Atualização: verificado que isso ja foi implementado)

**Comment by fredericomozzato** [comment]
Galera, eu e o @adoniranfranceh já tivemos que implementar a tela e a action edit para resolver nossa issue de deletar projeto. 

No momento ela só tem o botão de deletar projeto. Um detalhe que vimos é que no momento o botão de editar projeto aparece para qualquer ususário, então precisamos do condicional para somente o dono do projeto (ou administradores) verem este botão.

**Comment by olucasaguilar** [comment]
- [ ] Teste 1
- [ ] Teste 2
