### ISSUE TITLE
[Bug] Usuário não é redirecionado para edição de perfil

### ISSUE THREAD

**Issue by fredericomozzato** [TreinaDev/td11-cola-bora#29]
Ao criar uma conta, o usuário não está sendo redirecionado para a edição do perfil.

Em registrations_controller.rb, está sendo passado o id do user para o edit_profile_path ao invés do id do perfil.

Edit: O problema provavelmente está na criação dos seeds que gera um perfil duplicado para cada usuário, gerando um ID diferente para o perfil novo criado na aplicação, que fazia o método ```authorize``` no ```ProfilesController``` direcionar para a home.
No ```seeds.rb``` estava sendo usado o FactoryBot para criação direta de um novo perfil para o usuário, mas ele já é criado com um perfil associado, e nesse caso é necessário usar apenas o método update para atualizar o perfil já criado.

Estava assim:
```ruby
ash = FactoryBot.create(:user, email: 'ash@email.com', cpf: '837.513.746-47')
FactoryBot.create(:profile, user: ash, first_name: 'Ash', last_name: 'Ketchum',
                            work_experience: 'Treinador Pokemon', education: 'Escola Pokemon')
```

Utilizando o método update:
```ruby
ash = FactoryBot.create(:user, email: 'ash@email.com', cpf: '837.513.746-47')
ash.profile.update(first_name: 'Ash', last_name: 'Ketchum',
                            work_experience: 'Treinador Pokemon', education: 'Escola Pokemon')
```

**Comment by Luckvc** [comment]
Issue resolvida no merge #16
