### ISSUE TITLE
[Conta] Usuário edita perfil

### ISSUE THREAD

**Issue by MoisesssDev** [TreinaDev/td11-cola-bora#3]
Como um usuário autenticado, eu quero completar meu perfil com nome, sobrenome, experiência profissional e informação acadêmica, para ter meu perfil completo.

- Não obrigatório.
- [x] Testes de sistema
- [x] Testes unitários
- [x] Testes de requisição

**Comment by paulohenrique-gh** [comment]
- [x] Testes de sistema
- [ ] Testes unitários
- [ ] Testes de requisição
